services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - backend/diviconta:v1
        - backend/diviconta:latest
    volumes:
      - .:/backend
      - /backend/node_modules
    ports:
      - '3000:3000'
    command: npm run start
