import { Knex } from 'knex';
import { ETableNames } from '../ETableNames';

export const seed = async (knex: Knex) => {
  const [{ count }] = await knex(ETableNames.city).count<[{ count: number }]>(
    '* as count'
  );
  if (!Number.isInteger(count) || Number(count) > 0) return;

  const citiesToInsert = citiesSaoPaulo.map((cityName) => ({
    name: cityName,
  }));
  await knex(ETableNames.city).insert(citiesToInsert);
};

const citiesSaoPaulo = [
  'Adamantina',
  'Adolfo',
  'Aguaí',
  'Águas da Prata',
  'Águas de Lindóia',
  'Águas de Santa Bárbara',
  'Águas de São Pedro',
  'Agudos',
  'Alambari',
  'Alfredo Marcondes',
  'Altair',
  'Altinópolis',
  'Alto Alegre',
  'Alumínio',
  'Álvares Florence',
  'Álvares Machado',
  'Álvaro de Carvalho',
  'Alvinlândia',
  'Americana',
  'Américo Brasiliense',
  'Américo de Campos',
  'Amparo',
  'Analândia',
  'Andradina',
  'Angatuba',
  'Anhembi',
  'Anhumas',
  'Aparecida',
  "Aparecida d'Oeste",
  'Apiaí',
  'Araçariguama',
  'Araçatuba',
  'Araçoiaba da Serra',
  'Aramina',
  'Arandu',
  'Arapeí',
  'Araraquara',
  'Araras',
  'Arco-Íris',
  'Arealva',
  'Areias',
  'Areiópolis',
  'Ariranha',
  'Artur Nogueira',
  'Arujá',
  'Aspásia',
  'Assis',
  'Atibaia',
  'Auriflama',
  'Avaí',
  'Avanhandava',
  'Avaré',
  'Bady Bassitt',
  'Balbinos',
  'Bálsamo',
  'Bananal',

  'Gastão Vidigal',
  'Gavião Peixoto',
  'General Salgado',
  'Getulina',
  'Glicério',
  'Guaiçara',
  'Guaimbê',
  'Guaíra',
  'Guapiaçu',
  'Guapiara',
  'Guará',
  'Guaraçaí',
  'Guaraci',
  "Guarani d'Oeste",
  'Guarantã',
  'Guararapes',
  'Guararema',
  'Guaratinguetá',
  'Guareí',
  'Guariba',
  'Guarujá',
  'Guarulhos',
  'Guatapará',
  'Guzolândia',
  'Herculândia',
  'Holambra',
  'Hortolândia',
  'Iacanga',
  'Iacri',
  'Iaras',
  'Ibaté',
  'Ibirá',
  'Ibirarema',
  'Ibitinga',
  'Ibiúna',
  'Icém',
  'Iepê',
  'Igaraçu do Tietê',
  'Igarapava',
  'Igaratá',
  'Iguape',
  'Ilha Comprida',
  'Ilha Solteira',
  'Ilhabela',
  'Indaiatuba',
  'Indiana',
  'Indiaporã',
  'Inúbia Paulista',
  'Ipauçu',
  'Iperó',
  'Ipeúna',
  'Ipiguá',
  'Iporanga',
  'Ipuã',
  'Iracemápolis',
  'Irapuã',
  'Irapuru',
  'Itaberá',

  'Potim',
  'Potirendaba',
  'Pracinha',
  'Pradópolis',
  'Praia Grande',
  'Pratânia',
  'Presidente Alves',
  'Presidente Bernardes',
  'Presidente Epitácio',
  'Presidente Prudente',
  'Presidente Venceslau',
  'Promissão',
  'Quadra',
  'Quatá',
  'Queiroz',
  'Queluz',
  'Quintana',
  'Rafard',
  'Rancharia',
  'Redenção da Serra',
  'Regente Feijó',
  'Reginópolis',
  'Registro',
  'Restinga',
  'Ribeira',
  'Ribeirão Bonito',
  'Ribeirão Branco',
  'Ribeirão Corrente',
  'Ribeirão do Sul',
  'Ribeirão dos Índios',
  'Ribeirão Grande',
  'Ribeirão Pires',
  'Ribeirão Preto',
  'Rifaina',
  'Rincão',
  'Rinópolis',
  'Rio Claro',
  'Rio das Pedras',
  'Rio Grande da Serra',
  'Riolândia',
  'Riversul',
];
